### PR TITLE
PR template added

### PR DESCRIPTION
**Pull request by Wad098**
we add a Pull requst template

### CODE REVIEW

**Review by Irvingzhu73 — APPROVED** [review]
Great PR template

**Comment by BerBer-alt** [comment]
Great PR template

**Comment by BrightAurora138** [comment]
Good Pull Request Template

**Review by BerBer-alt — APPROVED** [review]
goodgood

**Review by BrightAurora138 — COMMENTED** [review]
Good Pull Request Template

**Comment by BrightAurora138** [comment]
Good Pull Request Template

**Review by BrightAurora138 — COMMENTED** [review]
Good Pull Request Template

**Review by BrightAurora138 — APPROVED** [review]
Good Pull Request Template

**Pull request merged**
